name    'goth-php5'
version '1.0.0'
source 'pirog'
author 'gothamcitydrupal'
license 'TBD'
summary 'PHP5.3 config'
description 'Contains PHP5.3 configuration optimized for drupal development'
project_page 'gothamcitydrupal.com'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
