name    'goth-mysql'
version '1.0.0'
source 'pirog'
author 'gothamcitydrupal'
license 'TBD'
summary 'MySQL config'
description 'Contains MySQL configuration optimized for drupal development'
project_page 'gothamcitydrupal.com'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
