name    'goth-apache'
version '0.0.1'
source 'UNKNOWN'
author 'gothamcitydrupal'
license 'TBD'
summary 'Apache config'
description 'Contains config to build apache optimized for drupal development'
project_page 'gothamcitydrupal.com'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
